#!/bin/sh
## verif_objdir for libmy in /home/benji_epitech/workdir/perso/libmy/lib/my/tools
## 
## Made by Benjamin Viguier
## Login   <benjamin.viguier@epitech.eu>
## 
## Started on  Mon May 22 18:53:34 2017 Benjamin Viguier
## Last update Mon May 22 18:53:35 2017 Benjamin Viguier
##

if [ -d "./obj" ];then
    echo "Le dossier 'obj' existe déjà."
else
    mkdir obj;
    echo "Crée."
fi
